fix in gh actions build_docs.yml

diff --git a/.github/workflows/build_docs.yml b/.github/workflows/build_docs.yml
--- a/.github/workflows/build_docs.yml
+++ b/.github/workflows/build_docs.yml
@@ -47,10 +47,10 @@ jobs:
           bash run_all.sh
       - name: Check mapping Code Result
         run: |
-        if [ $? -ne 0 ]; then
-          echo "Error: Python code failed"
-          exit 1
-        fi
+          if [ $? -ne 0 ]; then
+            echo "Error: Python code failed"
+            exit 1
+          fi
         shell: bash
       # Build the website
       - name: Build the site
